// web/src/routes/auth/login/+page.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Label } from '$lib/components/ui/label';
  import { Checkbox } from '$lib/components/ui/checkbox';
  import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '$lib/components/ui/card';
  import { auth } from '$lib/stores/auth';
  import { t } from '$lib/i18n';
  import { goto } from '$app/navigation';
  import { toast } from 'svelte-sonner';
  import { isValidEmail } from '$lib/utils';
  import { LanguageSwitcher } from '$lib/components/layout';
  import { onMount } from 'svelte';
  
  let email = $state('');
  let password = $state('');
  let rememberMe = $state(false);
  let isLoading = $state(false);
  let errors = $state({ email: '', password: '' });
  
  // Initialize with remembered email if available
  onMount(() => {
    const rememberedEmail = auth.getRememberedEmail();
    if (rememberedEmail) {
      email = rememberedEmail;
      rememberMe = true;
    }
  });
  
  // Redirect if already authenticated
  $effect(() => {
    if ($auth.isAuthenticated) {
      goto('/dashboard');
    }
  });
  
  // Validate form
  function validateForm() {
    let isValid = true;
    errors = { email: '', password: '' };
    
    if (!email) {
      errors.email = $t('required');
      isValid = false;
    } else if (!isValidEmail(email)) {
      errors.email = $t('invalidEmail');
      isValid = false;
    }
    
    if (!password) {
      errors.password = $t('required');
      isValid = false;
    }
    
    return isValid;
  }
  
  // Handle login
  async function handleLogin() {
    if (!validateForm()) return;
    
    isLoading = true;
    
    try {
      const result = await auth.login({ email, password, rememberMe });
      
      if (result.success) {
        toast.success($t('loginSuccessful'));
        goto('/dashboard');
      } else {
        toast.error(result.error || $t('somethingWentWrong'));
      }
    } catch (error) {
      toast.error($t('somethingWentWrong'));
    } finally {
      isLoading = false;
    }
  }
</script>

<div class="container flex h-screen w-screen flex-col items-center justify-center">
  <div class="absolute top-4 right-4">
    <LanguageSwitcher />
  </div>
  <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
    <div class="flex flex-col items-center justify-center space-y-2 text-center w-full">
      <h1 class="text-2xl font-semibold tracking-tight text-primary">{$t('appName')}</h1>
      <p class="text-sm text-muted-foreground">{$t('loginToYourAccount')}</p>
    </div>
    
    <Card>
      <CardContent>
        <form onsubmit={(e) => { e.preventDefault(); handleLogin(); }} class="space-y-4">
          <div class="space-y-2">
            <Label for="email">{$t('email')}</Label>
            <Input 
              id="email" 
              type="email" 
              bind:value={email} 
              placeholder="name@example.com" 
              autocomplete="email"
              class={errors.email ? 'border-destructive' : ''}
            />
            {#if errors.email}
              <p class="text-xs text-destructive">{errors.email}</p>
            {/if}
          </div>
          
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <Label for="password">{$t('password')}</Label>
            </div>
            <Input 
              id="password" 
              type="password" 
              bind:value={password} 
              autocomplete="current-password"
              class={errors.password ? 'border-destructive' : ''}
            />
            {#if errors.password}
              <p class="text-xs text-destructive">{errors.password}</p>
            {/if}
          </div>
          
          <div class="flex items-center justify-between">
            <div class="flex items-center">
              <Checkbox id="remember" bind:checked={rememberMe} />
              <Label for="remember" class="mx-2 text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                {$t('rememberMe')}
              </Label>
            </div>
            <a href="/auth/reset-password" class="text-xs text-primary hover:underline">
              {$t('forgotPassword')}
            </a>
          </div>
          
          <Button type="submit" class="w-full" disabled={isLoading}>
            {#if isLoading}
              <span class="mr-2">{$t('loading')}</span>
            {:else}
              {$t('login')}
            {/if}
          </Button>
        </form>
      </CardContent>
    </Card>
  </div>
</div>

// web/app/login/page.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { useAuth } from "@/app/context/auth-context";
import { useToast } from "@/components/ui/use-toast";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const { login } = useAuth();
  const router = useRouter();
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    
    try {
      await login(email, password);
      toast({
        title: "Login successful",
        description: "You have been logged in successfully.",
      });
      router.push("/dashboard"); // Redirect to dashboard after login
    } catch (error) {
      toast({
        title: "Login failed",
        description: "Please check your credentials and try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-50">
      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold text-center">Login</CardTitle>
          <CardDescription className="text-center">
            Enter your email and password to login to your account
          </CardDescription>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input 
                id="email" 
                type="email" 
                placeholder="name@example.com" 
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input 
                id="password" 
                type="password" 
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Checkbox id="remember" />
                <Label htmlFor="remember" className="text-sm font-normal">Remember me</Label>
              </div>
              <Link 
                href="/reset-password" 
                className="text-sm text-primary hover:underline"
              >
                Forgot password?
              </Link>
            </div>
          </CardContent>
          <CardFooter className="flex flex-col space-y-4 pt-4">
            <Button className="w-full mt-2" type="submit" disabled={isLoading}>
              {isLoading ? "Logging in..." : "Login"}
            </Button>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
