// web/src/routes/(authenticated)/customers/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { t } from '$lib/i18n';
  import { customersApi } from '$lib/services/api';
  import { toast } from 'svelte-sonner';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '$lib/components/ui/table';
  import { formatDate } from '$lib/utils';
  import type { Customer } from '$lib/types';
  import { Plus, Search } from 'lucide-svelte';
  
  let customers: Customer[] = [];
  let isLoading = true;
  let searchQuery = '';
  
  // Fetch customers
  async function fetchCustomers() {
    isLoading = true;
    
    try {
      const response = await customersApi.getAll();
      if (response.data) {
        customers = response.data;
      }
    } catch (error) {
      toast.error($t('somethingWentWrong'));
    } finally {
      isLoading = false;
    }
  }
  
  // Search customers
  async function searchCustomers() {
    if (!searchQuery.trim()) {
      fetchCustomers();
      return;
    }
    
    isLoading = true;
    
    try {
      const response = await customersApi.search(searchQuery);
      if (response.data) {
        customers = response.data;
      }
    } catch (error) {
      toast.error($t('somethingWentWrong'));
    } finally {
      isLoading = false;
    }
  }
  
  onMount(() => {
    fetchCustomers();
  });
</script>

<div>
  <div class="flex justify-between items-center mb-6">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">{$t('customers')}</h1>
      <p class="text-muted-foreground">{$t('customersList')}</p>
    </div>
    <Button>
      <Plus class="mr-2 h-4 w-4" />
      {$t('addCustomer')}
    </Button>
  </div>
  
  <div class="flex items-center mb-6">
    <div class="relative w-full max-w-sm">
      <Search class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
      <Input
        type="search"
        placeholder={$t('search')}
        class="pl-8"
        bind:value={searchQuery}
        on:keydown={(e) => e.key === 'Enter' && searchCustomers()}
      />
    </div>
    <Button variant="outline" class="ml-2" on:click={searchCustomers}>
      {$t('search')}
    </Button>
  </div>
  
  {#if isLoading}
    <div class="flex justify-center items-center h-64">
      <p>{$t('loading')}</p>
    </div>
  {:else if customers.length === 0}
    <div class="flex justify-center items-center h-64 border rounded-lg">
      <div class="text-center">
        <p class="text-muted-foreground">{$t('noCustomersFound')}</p>
        <Button variant="outline" class="mt-4" on:click={fetchCustomers}>
          {$t('refreshList')}
        </Button>
      </div>
    </div>
  {:else}
    <div class="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{$t('name')}</TableHead>
            <TableHead>{$t('email')}</TableHead>
            <TableHead>{$t('phone')}</TableHead>
            <TableHead>{$t('createdAt')}</TableHead>
            <TableHead class="text-right">{$t('actions')}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each customers as customer}
            <TableRow>
              <TableCell class="font-medium">{customer.name}</TableCell>
              <TableCell>{customer.email}</TableCell>
              <TableCell>{customer.phone}</TableCell>
              <TableCell>{formatDate(customer.createdAt)}</TableCell>
              <TableCell class="text-right">
                <Button variant="ghost" size="sm">
                  {$t('view')}
                </Button>
              </TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>
    </div>
  {/if}
</div>

// web/app/dashboard/customers/page.tsx
"use client";

import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Search, Plus, MoreHorizontal, Filter } from "lucide-react";
import { DashboardContainer } from "@/components/ui/dashboard-container";

// Mock customer data
const mockCustomers = [
  {
    id: "1",
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
    phone: "+1 (555) 123-4567",
    totalBookings: 5,
    lastBooking: "2023-12-15",
    status: "active",
  },
  {
    id: "2",
    name: "Olivia Smith",
    email: "olivia.smith@example.com",
    phone: "+1 (555) 234-5678",
    totalBookings: 3,
    lastBooking: "2023-11-20",
    status: "active",
  },
  {
    id: "3",
    name: "Sophia Williams",
    email: "sophia.williams@example.com",
    phone: "+1 (555) 345-6789",
    totalBookings: 7,
    lastBooking: "2024-01-05",
    status: "active",
  },
  {
    id: "4",
    name: "Isabella Brown",
    email: "isabella.brown@example.com",
    phone: "+1 (555) 456-7890",
    totalBookings: 2,
    lastBooking: "2023-10-10",
    status: "inactive",
  },
  {
    id: "5",
    name: "Ava Jones",
    email: "ava.jones@example.com",
    phone: "+1 (555) 567-8901",
    totalBookings: 4,
    lastBooking: "2023-12-28",
    status: "active",
  },
];

export default function CustomersPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState<string | null>(null);
  const [isAddCustomerOpen, setIsAddCustomerOpen] = useState(false);
  const [newCustomer, setNewCustomer] = useState({
    name: "",
    email: "",
    phone: "",
  });

  // Filter customers based on search term and status filter
  const filteredCustomers = mockCustomers.filter((customer) => {
    const matchesSearch =
      customer.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      customer.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
      customer.phone.includes(searchTerm);

    const matchesStatus =
      statusFilter === null || customer.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  const handleAddCustomer = () => {
    // In a real app, you would add the customer to the database
    console.log("Adding customer:", newCustomer);
    setIsAddCustomerOpen(false);
    setNewCustomer({ name: "", email: "", phone: "" });
  };

  return (
    <DashboardContainer>
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Customers</h2>
          <p className="text-muted-foreground">
            Manage your customer database
          </p>
        </div>
        <Dialog open={isAddCustomerOpen} onOpenChange={setIsAddCustomerOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Add Customer
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Add New Customer</DialogTitle>
              <DialogDescription>
                Enter the details of the new customer.
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Full Name</Label>
                <Input
                  id="name"
                  value={newCustomer.name}
                  onChange={(e) =>
                    setNewCustomer({ ...newCustomer, name: e.target.value })
                  }
                  placeholder="John Doe"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  value={newCustomer.email}
                  onChange={(e) =>
                    setNewCustomer({ ...newCustomer, email: e.target.value })
                  }
                  placeholder="john.doe@example.com"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="phone">Phone Number</Label>
                <Input
                  id="phone"
                  value={newCustomer.phone}
                  onChange={(e) =>
                    setNewCustomer({ ...newCustomer, phone: e.target.value })
                  }
                  placeholder="+1 (555) 123-4567"
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsAddCustomerOpen(false)}>
                Cancel
              </Button>
              <Button onClick={handleAddCustomer}>Add Customer</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Customer Management</CardTitle>
          <CardDescription>
            View and manage all your customers
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between mb-4">
            <div className="relative w-full max-w-sm">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Search customers..."
                className="pl-8"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm">
                  <Filter className="mr-2 h-4 w-4" />
                  Filter
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Filter by Status</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={() => setStatusFilter(null)}>
                  <Checkbox
                    checked={statusFilter === null}
                    className="mr-2"
                    id="all"
                  />
                  <label htmlFor="all">All</label>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => setStatusFilter("active")}>
                  <Checkbox
                    checked={statusFilter === "active"}
                    className="mr-2"
                    id="active"
                  />
                  <label htmlFor="active">Active</label>
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => setStatusFilter("inactive")}>
                  <Checkbox
                    checked={statusFilter === "inactive"}
                    className="mr-2"
                    id="inactive"
                  />
                  <label htmlFor="inactive">Inactive</label>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Phone</TableHead>
                  <TableHead>Total Bookings</TableHead>
                  <TableHead>Last Booking</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="w-[80px]"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredCustomers.map((customer) => (
                  <TableRow key={customer.id}>
                    <TableCell className="font-medium">{customer.name}</TableCell>
                    <TableCell>{customer.email}</TableCell>
                    <TableCell>{customer.phone}</TableCell>
                    <TableCell>{customer.totalBookings}</TableCell>
                    <TableCell>{new Date(customer.lastBooking).toLocaleDateString()}</TableCell>
                    <TableCell>
                      <span
                        className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                          customer.status === "active"
                            ? "bg-green-100 text-green-800"
                            : "bg-red-100 text-red-800"
                        }`}
                      >
                        {customer.status}
                      </span>
                    </TableCell>
                    <TableCell>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon">
                            <MoreHorizontal className="h-4 w-4" />
                            <span className="sr-only">Open menu</span>
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuLabel>Actions</DropdownMenuLabel>
                          <DropdownMenuItem>View details</DropdownMenuItem>
                          <DropdownMenuItem>Edit customer</DropdownMenuItem>
                          <DropdownMenuSeparator />
                          <DropdownMenuItem className="text-red-600">
                            Delete customer
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))}
                {filteredCustomers.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={7} className="h-24 text-center">
                      No customers found.
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </DashboardContainer>
  );
}
