// web/src/routes/auth/reset-password/+page.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Label } from '$lib/components/ui/label';
  import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '$lib/components/ui/card';
  import { auth } from '$lib/stores/auth';
  import { t } from '$lib/i18n';
  import { goto } from '$app/navigation';
  import { toast } from 'svelte-sonner';
  import { isValidEmail } from '$lib/utils';
  
  let email = '';
  let isLoading = false;
  let emailSent = false;
  let error = '';
  
  // Redirect if already authenticated
  $effect(() => {
    if ($auth.isAuthenticated) {
      goto('/dashboard');
    }
  });
  
  // Handle reset password request
  async function handleResetPassword() {
    if (!email) {
      error = $t('required');
      return;
    }
    
    if (!isValidEmail(email)) {
      error = $t('invalidEmail');
      return;
    }
    
    error = '';
    isLoading = true;
    
    try {
      const result = await auth.resetPassword({ email });
      
      if (result.success) {
        emailSent = true;
        toast.success($t('resetLinkSent'));
      } else {
        toast.error(result.error || $t('somethingWentWrong'));
      }
    } catch (error) {
      toast.error($t('somethingWentWrong'));
    } finally {
      isLoading = false;
    }
  }
</script>

<div class="container flex h-screen w-screen flex-col items-center justify-center">
  <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
    <div class="flex flex-col space-y-2 text-center">
      <h1 class="text-2xl font-semibold tracking-tight text-primary">{$t('appName')}</h1>
      <p class="text-sm text-muted-foreground">
        {emailSent ? $t('checkYourEmail') : $t('resetYourPassword')}
      </p>
    </div>
    
    <Card>
      <CardHeader>
        <CardTitle>{$t('resetPassword')}</CardTitle>
        <CardDescription>
          {emailSent ? $t('resetLinkSentDescription') : $t('enterYourEmail')}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {#if !emailSent}
          <form on:submit|preventDefault={handleResetPassword} class="space-y-4">
            <div class="space-y-2">
              <Label for="email">{$t('email')}</Label>
              <Input 
                id="email" 
                type="email" 
                bind:value={email} 
                placeholder="name@example.com" 
                autocomplete="email"
                class={error ? 'border-destructive' : ''}
              />
              {#if error}
                <p class="text-xs text-destructive">{error}</p>
              {/if}
            </div>
            
            <Button type="submit" class="w-full" disabled={isLoading}>
              {#if isLoading}
                <span class="mr-2">{$t('loading')}</span>
              {:else}
                {$t('sendResetLink')}
              {/if}
            </Button>
          </form>
        {:else}
          <div class="text-center py-4">
            <p class="text-sm text-muted-foreground mb-4">
              {$t('resetLinkSentLong')}
            </p>
            <Button variant="outline" on:click={() => goto('/auth/login')}>
              {$t('backToLogin')}
            </Button>
          </div>
        {/if}
      </CardContent>
      <CardFooter>
        <div class="text-center w-full">
          <a href="/auth/login" class="text-xs text-primary hover:underline">
            {$t('rememberPassword')}
          </a>
        </div>
      </CardFooter>
    </Card>
  </div>
</div>

// web/app/reset-password/page.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/app/context/auth-context";
import { useToast } from "@/components/ui/use-toast";

export default function ResetPasswordPage() {
  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const { requestPasswordReset } = useAuth();
  const { toast } = useToast();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    
    try {
      await requestPasswordReset(email);
      setIsSubmitted(true);
      toast({
        title: "Reset link sent",
        description: "If an account exists with this email, you will receive a password reset link.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "There was a problem sending the reset link. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-50">
      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1">
          <CardTitle className="text-2xl font-bold text-center">Reset Password</CardTitle>
          <CardDescription className="text-center">
            {isSubmitted 
              ? "Check your email for a reset link"
              : "Enter your email address and we'll send you a link to reset your password"}
          </CardDescription>
        </CardHeader>
        {!isSubmitted ? (
          <form onSubmit={handleSubmit}>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input 
                  id="email" 
                  type="email" 
                  placeholder="name@example.com" 
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
            </CardContent>
            <CardFooter className="flex flex-col space-y-4 pt-4">
              <Button className="w-full mt-2" type="submit" disabled={isLoading}>
                {isLoading ? "Sending..." : "Send Reset Link"}
              </Button>
              <div className="text-center text-sm mt-2">
                Remember your password?{" "}
                <Link href="/login" className="text-primary hover:underline">
                  Back to login
                </Link>
              </div>
            </CardFooter>
          </form>
        ) : (
          <CardContent className="space-y-4">
            <div className="text-center p-4">
              <p className="mb-4">
                We've sent a password reset link to <strong>{email}</strong>
              </p>
              <p className="text-sm text-muted-foreground">
                Please check your email and click on the link to reset your password.
                If you don't see it, check your spam folder.
              </p>
            </div>
            <Button 
              variant="outline" 
              className="w-full" 
              onClick={() => setIsSubmitted(false)}
            >
              Try another email
            </Button>
            <div className="text-center text-sm">
              <Link href="/login" className="text-primary hover:underline">
                Back to login
              </Link>
            </div>
          </CardContent>
        )}
      </Card>
    </div>
  );
}
